### ISSUE TITLE
Parse Exercise Markers in Pump History

### ISSUE THREAD

**Issue by channemann** [loudnate/openaps-mmhistorytools#25]
Bridging https://github.com/bewest/decoding-carelink/issues/126 and https://github.com/loudnate/openaps-predict/issues/13

**Comment by channemann** [comment]
See https://github.com/loudnate/openaps-mmhistorytools/pull/27

**Comment by loudnate** [comment]
Fixed in Version 0.1.0, which will be tagged tomorrow.
