### ISSUE TITLE
Handle Reservoir + Set (Set Change) as Suspend

### ISSUE THREAD

**Issue by channemann** [loudnate/openaps-mmhistorytools#38]
Pump was removed and the set change process started, then I left it in the fully rewound state and took a shower. After getting out, completed set change (replaced reservoir, primed), but cleaned history did not reflect this effective "suspend". I believe there may have been a scheduled basal change that occurred in the middle, so the rewind and two prime history entries may have been nonconsecutive.

I don't have the history files to show this as my SD card died before I uploaded them, unfortunately.

**Comment by loudnate** [comment]
This is already filed as #36. Please attach any test data to that ticket as you get it.
